checks:
    php:
        code_rating: true
        duplication: true
        excluded_dependencies:
              - zacksleo/metronic
              - monster-hunter/metronic
              - monsterhunter/metronic