language: php

matrix:
  fast_finish: true

php:
  #- 5.6
  - 7.1

  # cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

services:
  - mysql

install:
 # - chmod 0600 ~/.ssh/id_rsa
 # - ssh-add ~/.ssh/id_rsa
 # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - composer config -g github-oauth.github.com caf16441da5ba578b34a765e67e3bf2ad1941389
  - travis_retry mysql -e 'CREATE DATABASE test;'

before_script:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in ./tests/.ssh/id_rsa.enc -out ~/.ssh/id_rsa -d
  - eval $(ssh-agent -s)
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
