language: php
matrix:
  fast_finish: true
php:
- 7.1
cache:
  directories:
  - "$HOME/.composer/cache"
  - vendor
services:
- mysql
install:
- composer config -g github-oauth.github.com caf16441da5ba578b34a765e67e3bf2ad1941389
- travis_retry mysql -e 'CREATE DATABASE test;'
before_script:
- travis_retry composer self-update
- composer config repositories.metronic vcs git@gitlab.com:zacksleo/monster-hunter/metronic.git
- composer require zacksleo/metronic --prefer-dist
- composer require zacksleo/metronic --prefer-dist
- composer install --prefer-dist --no-interaction
script:
- "./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover"
after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
before_install:
- openssl aes-256-cbc -K $encrypted_0eed4f6a8a84_key -iv $encrypted_0eed4f6a8a84_iv
  -in ./tests/.ssh/id_rsa.enc -out id_rsa -d
